name: ECR & Cloud-formation deployment

inputs:
  # Required inputs
  ENVIRONMENT:
    type: string
    description: "Name of the environment to deploy"
    required: true
  AWS_CF_STACK_NAME:
    type: string
    description: "AWS cloud-formation stack name"
    required: true
  AWS_ECR_REPOSITORY:
    type: string
    description: "AWS ECR Repository name"
    required: true
  AWS_ACCESS_KEY_ID:
    type: string
    description: "AWS Access key id"
    required: true
  AWS_SECRET_ACCESS_KEY:
    type: string
    description: "AWS Secret access key"
    required: true
  AWS_REGION:
    type: string
    description: "AWS Region"
    required: true
  
  # NOT required inputs
  CAPABILITIES:
    description: "The comma-delimited list of stack template capabilities to acknowledge. Defaults to 'CAPABILITY_IAM'"
    required: false
  AWS_CLOUDFORMATION_PARAMS_OVERRIDE:
    type: string
    description: "Cloudformation parameters to override when deploy the application"
    required: false
  TAG:
    type: string
    description: Tag that will be placed on the docker image to upload in ECR. The default value is the Short commit SHA.
    required: false
  DISABLE_CACHE:
    type: boolean
    default: false
    description: Disable docker cache
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Get Short commit SHA if don't send a TAG
      shell: bash
      run: |
        if [ '${{ inputs.TAG }}' == '' ]; then
          echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV;
        else
          echo "TAG=${{ inputs.TAG }}" >> $GITHUB_ENV;
        fi

    - uses: aws-actions/configure-aws-credentials@v1-node16
      id: AWS
      with:
        aws-access-key-id:      ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key:  ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region:             ${{ inputs.AWS_REGION }}
    
    - name: Form ECR Docker URL
      shell: bash
      run: echo ECR_URL=${{ steps.AWS.outputs.aws-account-id }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.AWS_ECR_REPOSITORY }} >> $GITHUB_ENV

    - name: Log-in to ECR
      shell: bash
      run: aws ecr get-login-password --region "${{ inputs.AWS_REGION }}" | docker login --username AWS --password-stdin ${{ env.ECR_URL }}

    - name: Verify if Docker already exist with tag ${{ env.TAG }}
      shell: bash
      run: |
        IMAGE=$(aws ecr list-images --repository-name ${{ inputs.AWS_ECR_REPOSITORY }} --query "imageIds[?imageTag=='${{ env.TAG }}'].imageDigest" --output text)
        echo EXITS_IMAGE=$(if [[ ! -z "${IMAGE}" ]]; then echo true; else echo false; fi) >> $GITHUB_ENV

    - name: Modify package.json based on bumped tag
      if: env.EXITS_IMAGE != 'true'
      shell: bash
      run: |
        echo sed -i 's/\"version\":\s*\"[0-9]+\.[0-9]+\.[0-9]+\",\"version\": \"${{ env.TAG }}\"/g' package.json

    - name: Get latest image commit sha
      if: env.EXITS_IMAGE != 'true' && inputs.DISABLE_CACHE != 'true'
      shell: bash
      run: |
        latest_sha=$(aws ecr describe-images --repository-name ${{ inputs.AWS_ECR_REPOSITORY }} --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)
        echo LATEST_TAG=$latest_sha >> $GITHUB_ENV

    - name: Docker build and push with cache inlined
      if: env.EXITS_IMAGE != 'true' && inputs.DISABLE_CACHE != 'true' && env.LATEST_TAG != 'None'
      shell: bash
      run: >
        docker buildx build
        --push -t ${{ env.ECR_URL }}:${{ env.TAG }}
        --cache-to=type=inline
        --cache-from=type=registry,ref=${{ env.ECR_URL }}:${{ env.LATEST_TAG }}
        .

    - name: Docker build and push no cache
      if: env.EXITS_IMAGE != 'true' && (inputs.DISABLE_CACHE == 'true' || env.LATEST_TAG == 'None')
      shell: bash
      run: >-
        docker buildx build
        --push -t ${{ env.ECR_URL }}:${{ env.TAG }}
        --cache-to=type=inline
        .

    - name: Prefix parameter overrides Cloud Formation
      shell: bash
      run: |
        HAVE_PARAMS=${{ contains(inputs.AWS_CLOUDFORMATION_PARAMS_OVERRIDE, '=') }}
        echo "PREFIX_OVERRIDE=$(if [ $HAVE_PARAMS == 'true' ]; then echo ','; else echo ''; fi)" >> $GITHUB_ENV

    - name: Capitalize environment
      id: CAPITALIZED_ENV
      uses: ASzc/change-string-case-action@v5
      with:
          string: ${{ inputs.ENVIRONMENT }}

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      env:
        ENV_CAPITALIZED: ${{ steps.CAPITALIZED_ENV.outputs.capitalized }}
      with:
        name: ${{ inputs.AWS_CF_STACK_NAME }}-${{ inputs.ENVIRONMENT }}
        template: ./cloudformation/cloudformation.yml
        capabilities: ${{ inputs.CAPABILITIES }}
        parameter-overrides: >-
          Environment=${{ inputs.ENVIRONMENT }},
          ParameterSuffix=${{ env.ENV_CAPITALIZED }},
          EnvAwsECRImage=${{ inputs.AWS_ECR_REPOSITORY }}:${{ env.TAG }}
          ${{ env.PREFIX_OVERRIDE }} ${{ inputs.AWS_CLOUDFORMATION_PARAMS_OVERRIDE }}
